### ISSUE TITLE
Mod file 'DebugMod.dll' failed to load

### ISSUE THREAD

**Issue by dotada** [oxygencraft/DebugMod#16]
I know this mod is discontinued but I wanted to try it anyway to see what would happen. Today I booted it up and got this

Pathfinder [ERROR]: Mod file 'DebugMod.dll' failed to load:
        System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Pathfinder.ModManager.Manager.LoadMods(String path, String modId)
   at Pathfinder.ModManager.Manager.TryLoadMods(String path)
   
   
   I post this here incse it somehow gets noticed

**Comment by dotada** [comment]
Wait I just joined the discord and looked at the FAQ.
